version: '3'

services:
 lab:
   restart: always
#   image: laba1
   build:
     context: ./opt
     dockerfile: Dockerfile
   volumes: [ "./opt:/opt" ]
   environment:
     PORT: "5000"
     FLASK_DEBUG: "true"
   ports:
     - "5000:5000"